services:
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.21.0
    container_name: salao-jaeger
    ports:
      - "127.0.0.1:16686:16686"
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:4318:4318"
    restart: unless-stopped